name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: docker build ./DefaultMvcCore8 --tag mvccore8sampleproj:${{ github.sha }}

    - name: Push the Docker image to Docker Hub
      run: |
        docker tag mvccore8sampleproj:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/mvccore8sampleproj:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/mvccore8sampleproj:${{ github.sha }}
